### ISSUE TITLE
Per_page and page arguments lost when using search

### ISSUE THREAD

**Issue by steelcm** [cravindra/pexels-api-wrapper#9]

**Comment by cravindra** [comment]
Hello! @steelcm can you elaborate a little on what you are seeing?

**Comment by cihancahit** [comment]
``    var search = query ? "query=" + encodeURIComponent(query) + "&per_page=" + (perPage && !isNaN(perPage) ? +perPage : 10)
    + "&page=" + (page && !isNaN(page) ? +page : 1) : ""
        + "&per_page=" + (perPage && !isNaN(perPage) ? +perPage : 10)
        + "&page=" + (page && !isNaN(page) ? +page : 1);

> I don't know if this is the correct method but it works

**Comment by cravindra** [comment]
HI folks, thanks for the report and the fix - sorry, haven't been able to stay on top of this project - will archive it to make it better visible up front
